### ISSUE TITLE
Map height

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-dp-2016#28]
The map looks good and fills the area well, but it seems to have an extra area which is added to the entire application in the embed. 

![iframe_example_of_2015_map_of_death_penalties_and_execution_around_the_world_-_amnesty_international](https://cloud.githubusercontent.com/assets/1565953/16410464/82e71168-3d1a-11e6-830a-1bf29243d3ec.png)

**Comment by robertocarroll** [comment]
Suggestion to try removing countries at the top of the globe. Perhaps Greenland / top of Canada.

**Comment by robertocarroll** [comment]
After changing projection (see #37) the map needs some size and scale tweaks to fill the space.

**Comment by robertocarroll** [comment]
Perhaps setting the initial zoom a couple of notches higher would sort the initial view with this projection? What do you reckon? 

Not sure about the height thing.

**Comment by pauldwaite** [comment]
Possibly — although I’m not very familiar with D3’s geo module, I guess we set this stuff mostly here:

```
projection = d3.geo.naturalEarth()
  .center([-15, YPosition ])
  .translate([(width/2-30), (height/2)])
  .scale( width / 1.5 / Math.PI);
```

And we use the `scaleAdjust` variable to work out the height from the width (giving us different dimensions at different screen sizes).

I could play around with these to see if we can make the SVG tighter. I _think_ D3’s documentation says that [the default translation](https://github.com/d3/d3-geo/blob/master/README.md#projection_translate) of the projection puts it in the center of a the center of a 960×500 area, so maybe that ratio is a good starting point.

**Comment by pauldwaite** [comment]
I’ve been playing around a bit, but I’m still a bit confused about how the various projection methods affect the map rendering. I’ll read up a bit more and try to understand what’s going on.

**Comment by robertocarroll** [comment]
Seems OK on most layouts with current projection.
