### ISSUE TITLE
"flip" bar chart

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-dp-2016#33]
Bar chart needs to go in the opposite direction.

**Comment by robertocarroll** [comment]
Great stuff @pauldwaite  Thanks! One tiny thing: the bar chart hover needs to be positioned differently for rtl. 

Line 553 - changing the left value to something like -115 would work if (dir === "rtl"), but I wanted to check with you.

**Comment by pauldwaite** [comment]
Ah yes. I may have fixed this — I’m not 100% what tooltip position we want, but I’ve now changed it so that in RTL, the tooltip is positioned to the left of the mouse cursor, instead of the right.

Is that correct? Or do we want something else?

**Comment by robertocarroll** [comment]
Excellent. Thanks. I'll copy that technique for the map tooltips.
