### ISSUE TITLE
Executions / DP boxes side by side in detailbox

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-dp-2016#34]
Agreed to take another look at this as in the original designs.

**Comment by robertocarroll** [comment]
@pauldwaite we need to include the status definition in the detailbox below the status. 
- is it `dictionary.getTranslation('COUNTRIES')`?

![dpmap_desktopfinalwireframe copy](https://cloud.githubusercontent.com/assets/1565953/16844157/eda5d854-49db-11e6-87c1-38e246378755.png)

A couple of related questions: 
- is the height of the detailbox fixed? Can we provide more height to make room for the definition? 
- The death penalty and execution figures are meant to be side by side. What do you think about using a table to achieve two fixed height fluid columns side by side?

**Comment by pauldwaite** [comment]
Ah yes — I think I must have made a mistake when doing the localisation that lost the status description from the detail box. I’ve put it back in now, although it’s in an `<h3>` tag, and the styling is different (bolder) to that screenshot.

**Comment by pauldwaite** [comment]
> What do you think about using a table to achieve two fixed height fluid columns side by side?

Sounds good.

> is the height of the detailbox fixed?

Right now it’s as tall as `#info-box-inner` (minus space at the top to allow the year to still be visible), which is only as tall as its contents.

I guess we never really know how much vertical space we have for this component, as it could be included anywhere. And I guess we don’t want the whole thing to be scrollable? So I think maybe the detail box itself will need to have its content be scrollable?

**Comment by robertocarroll** [comment]
I think I fixed the side by side but opening a couple of new issues for the detailbox height and the sizing of the icon / figures.
