### ISSUE TITLE
Do we need country name in data.json?

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-dp-2016#35]
If we have the ISO3 code in the ID and the country names are in the dictionary file, do we need the country names in the data?

**Comment by robertocarroll** [comment]
@pauldwaite if you get a moment, would you mind thinking about the question above. It occurred to me that we could possibly eliminate the country name, e.g. "name":"Angola" from the data.json because we already have the ISO3 code. It would be good for keeping the data clean, but would it be a lot of work to implement?

**Comment by pauldwaite** [comment]
Ah yes — we no longer use the `name` property of the country data — we loop through all the countries and add a `name__localised` property using the dictionary, and use that everywhere.

So, if the name property is eliminated from all countries in data.json, everything should continue to work as it does now.

**Comment by robertocarroll** [comment]
Excellent. I'll delete it and give it a try. Thanks!
