### ISSUE TITLE
Position the map below the infobox in mobile view

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-dp-2016#41]
At the moment, the map sits over the infobox. It's OK until you use the zoom, then it goes a bit crazy. z-index doesn't seem to work.

**Comment by pauldwaite** [comment]
I haven’t been able to reproduce this in Chrome on my Mac. Where are you seeing it?

**Comment by robertocarroll** [comment]
This seems OK now. Closing this issue.
