### ISSUE TITLE
Map height changes with timeline 

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-dp-2016#42]
> Upon first clicking play the map height increases slightly, and then readjusts again as the pointer passes 2008. This seems to occur at different screen sizes, and for both world and country specific views

**Comment by pauldwaite** [comment]
I haven’t been able to reproduce this yet. Maybe my change for issue #29 removed the problem?

**Comment by robertocarroll** [comment]
Does seem to be fixed now.
