### ISSUE TITLE
Replace pym.js with iframe-resizer

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-dp-2016#64]
As explained by Tristan Ashley <tristan.ashley@codecomputerlove.com> and Gavin Cooke <gavin.cooke@codecomputerlove.com> on e-mail, amnesty.org already implements David J. Bradshaw’s iframe-resizer, which carries out the same function as pym.js.

As such, we should implement iframe-resizer in the map, so that we take advantage of the script they already have deployed, instead of making them introduce another script that does the same thing.

**Comment by pauldwaite** [comment]
Hi Rob! I’ve e-mailed you describing this change.

I’ve just assigned the ticket to you so that you can confirm whether I’m alright to merge it into v2-all/gh-pages/another branch/etc.

**Comment by robertocarroll** [comment]
Thanks @pauldwaite Sorry I should have said we're working in gh-pages now. Did you create your new branch from gh-pages or v2-all?

**Comment by paulwaitehomeoffice** [comment]
Ah yes of course — no worries, I should have checked really.

I branched `replace-pym-with-iframe-resizer` from `v2-all`. However, I’ve just merged `gh-pages` into `replace-pym-with-iframe-resizer`, and there were no conflicts (it just updated `data.json`).

So, if I’m understanding my git stuff right, you can merge `replace-pym-with-iframe-resizer` into `gh-pages` whenever you want, and we’ll be done.

**Comment by paulwaitehomeoffice** [comment]
Pull request created: https://github.com/wearethoughtfox/amnesty-dp-2016/pull/65

**Comment by robertocarroll** [comment]
Doh! That was early morning typing for you. Of course it would keep any new commits! I suppose the clue is in the word **MERGE**! Sorry about that. Thanks!

**Comment by paulwaitehomeoffice** [comment]
@robertocarroll Naw nothing about Git is actually obvious. As [a wise man once said](https://twitter.com/tabqwerty/status/45611899953491968), git gets easier once you get the basic idea that branches are homeomorphic endofunctors mapping submanifolds of a Hilbert space. (See also https://xkcd.com/1597/)
